[package]
name = "day09"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../../lib/common" }
color-eyre = { workspace = true }
rstest = { workspace = true }
nom = { workspace = true }
derive_more = "0.99"
egui = "0.22"
eframe = "0.22"
