[package]
name = "day12"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
common = { path = "../../lib/common" }
color-eyre = { workspace = true }
rstest = { workspace = true }
grid = "0.10.0"
wasm-bindgen = "0.2"
svg = "0.13"
console_error_panic_hook = "0.1.7"
web-sys = { version = "0.3.64", features = ["console"] }
